### ISSUE TITLE
As a Dev, I need a dev environment

### ISSUE THREAD

**Issue by OpenPointers** [OpenPointers/wordpress#8]
Let's build a [Vuetify](https://vuetifyjs.com/en/) front end and use WordPress as our backend (via the [WordPress REST API](https://developer.wordpress.org/rest-api/)). The benefits to this are:

- Very fast development cycle
  - No need for a local LAMP setup since we'll use REST
  - Can run standalone (as a SPA on Firebase) or as a complete WordPress/Drupal/etc theme with minimal code change
  - Component hot reload means that we don't have to reinitialize the webcam/model each time
- Turn key-able
  - If we keep it small, we can use it as a base to create other projects etc

# Tasks
Let's just focus on getting a "coming soon" page visible at openpointers.org using Vuetify in WordPress. We'll actually connect the two in later stories

## Vue
- [x] Install Vuetify
- [x] Change basic branding (title, favicon)
- [x] Create an ultra lightweight splash screen that loads before even Vuetify does...goal is to have it load instantly
- This will eventually be re-used as a loading screen (like Hearthstone's loading screens)
![twitter-header](https://user-images.githubusercontent.com/47646970/52876950-82c81f80-310d-11e9-913a-298cd267ac4d.png)

## WordPress Tasks
- [x] Install an empty WordPress site
- [x] Point domains
- [x] Setup backups
- [x] Create required WordPress files (functions.php, screenshot.png, etc)
- [x] Deploy

## Cleanup
- [x] README with wiki to document how to setup and install the theme

**Comment by OpenPointers** [comment]
Done, https://OpenPointers.org is now "live" with a splash screen:

![image](https://user-images.githubusercontent.com/47646970/52895069-b9338800-3169-11e9-9372-d6f88c7654bd.png)
